server:
  port: 2023

spring:
  redis:
    port: 63796
    host: 127.0.0.1
    password: 123456
    timeout: 5000
##    password: 123456
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 500
#        min-idle: 0
#    lettuce:
#      shutdown-timeout: 0